### ISSUE TITLE
Function timed out after 30 seconds (maxMemoryUsage: 47.28MB)

### ISSUE THREAD

**Issue by CrazyBunQnQ** [dyc87112/OpenAIProxy#3]
经常返回 `{"errorMessage":"Function timed out after 30 seconds (maxMemoryUsage: 47.28MB)"}`

是不是修改[这个 timeout](https://github.com/dyc87112/OpenAIProxy/blob/73d393b73b7930196de2223a0fd291fcde0712a6/src/s.yaml#L23)就好了？

```yaml
diskSize: 512
runtime: custom
caPort: 9000
timeout: 30
```

另外我是点一键部署的，怎么能部署修改后的配置呢？
